### PR TITLE
WIP: Add GNOME 3.32 support

### PR DESCRIPTION
**Pull request by tallero**
Mutter [deprecated](https://gitlab.gnome.org/GNOME/mutter/merge_requests/221) `_GTK_HIDE_TITLEBAR_WHEN_MAXIMIZED`, so the extension is not working on shell 3.32.

At this stage I fixed the warning about ByteArray.toString() and replaced the occurrences of  `_GTK_HIDE_TITLEBAR_WHEN_MAXIMIZED` with `_MOTIF_WM_HINTS`.

Because of the deprecation now the extension has to track un/maximized window states, so at the moment it just hides titlebars of all X.org windows, maximized or not.

### CODE REVIEW

**Comment by bargst** [comment]
This patch worked for me.

**Comment by tallero** [comment]
It needs to be fixed, though.

**Comment by andrewfader** [comment]
It works for me

**Comment by andrewfader** [comment]
I spoke too soon. It makes the window titlebars and borders go away, but all the time, like you said. Which also has the effect of making some windows impossible to move or resize

**Comment by jwarkentin** [comment]
FWIW, I've wanted the ability to selectively make titlebars and borders go away on unmaximized windows for a long time. It's easy to move any window by holding the meta/super key and clicking anywhere on the window to drag. I'm so used to doing that since the early days of Compiz/Compiz Fusion that I don't even attempt to use the titlebars for that. I just want to get rid of the useless and often terrible looking waste of space that titlebars are, regardless of maximized state.

**Comment by andrewfader** [comment]
@jwarkentin thanks for the tip. I will try using this Pixel Saver for a while and see if I can retrain my mind to use the meta+click drag. I already use Put Windows for super+M to maximize and super+directional to move.

**Comment by SpaceboyRoss01** [comment]
So with 3.32 support, it wont be buggy as shit?

**Comment by tallero** [comment]
@SpaceboyRoss01 Actually this patch is incomplete. What bug do you have?

**Comment by SpaceboyRoss01** [comment]
See #198

**Comment by tallero** [comment]
You can still move and resize them using shortcuts or super+mouse button.
In any case to solve this, pixel saver has to track the maximized status of the window,  which now does not happen because the gtk flag did this at toolkit level.

I didn't work on this because atm I am heavily using barrier (ex synergy) which breaks even on gnome 3.30 when pixel saver is enabled.

Il 23 marzo 2019 17:59:10 CET, Andrew Fader <notifications@github.com> ha scritto:
>I spoke too soon. It makes the window titlebars and borders go away,
>but all the time, like you said. Which also has the effect of making
>some windows impossible to move or resize
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/deadalnix/pixel-saver/pull/191#issuecomment-475886372

-- 
Inviato dal mio dispositivo Android con K-9 Mail. Perdonate la brevità.

**Comment by demon101** [comment]
+1

**Pull request merged**
