### PR TITLE
fix: global.screen is replaced by globa.window_manager in latest gnom…

### PR DESCRIPTION
**Pull request by ildella**
This patch works in latest ubuntu 18.10
original code branched from 1.10

### CODE REVIEW

**Comment by gbraad** [comment]
@deadalnix do you have a suggestion how to go about this?

**Comment by tallero** [comment]
@ildella I am using GNOME Shell 3.30.2 and upstream extension works. What is this all about?

**Comment by jhpratt** [comment]
Any plans to merge this?

**Comment by tallero** [comment]
@jhpratt the same change has already been merged in #174, we should close this request.

**Pull request closed without merging**
